language: node_js
node_js:
  - "8"

install:
  - npm install

script:
  - npm run build

after_success:
  - cd ./dist
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/simple-delfino/music.git
    - GH_TOKEN: 920f496a6b48578948977bdc0083a28dc386696c
    - P_BRANCH: gh-pages
    - U_EMILE: 1319879149@qq.com
    - U_NAME: simple-delfino
